(define (square-equation a b c)
  (define disk 0)
  (define x1 0)
  (define x2 0)
  (set! disk (-(* b b) (* 4 a c)))
  (if (> disk 0)
      (set! x1 (/(-(- b)(sqrt disk)) (* 2 a))))
  (if (> disk 0)
      (set! x2 (/(+(- b)(sqrt disk)) (* 2 a))))
  (if (= disk 0) 
      (set! x1 (list(/(- 0 b) (* 2 a)))))
  (if (< disk 0)
      (set! x1 '()))
  (if (> disk 0)
      (list x1 x2)
      x1))
